### ISSUE TITLE
cannot read property 'readerQR' of undefined

### ISSUE THREAD

**Issue by gaozhaopei** [LewinJun/react-native-lewin-qrcode#10]
import {readerQR} from 'react-native-lewin-qrcode'

  readerQR(path).then((data)=>{
            this.setState({reader: {
              message: '识别成功',
              data: data
            }});
            // 十秒后自动清空
            setTimeout(() => {
              this.setState({reader: {
                message: null,
                data: null
              }})
            }, 10000);
          }).catch((err)=>{
            this.setState({reader: {
              message: '识别失败',
              data: null
            }});
          });

代码如上 报错cannot read property 'readerQR' of undefined

**Comment by LewinJun** [comment]
这个明显库还没有引用进来，link了没？或者手动link, 你用的是RN 0.60+吗

**Comment by LewinJun** [comment]
目前暂时关闭了，如有需要欢迎再提issue
