### ISSUE TITLE
null is not object (evaluating 'QRScanReader.readerQr)

### ISSUE THREAD

**Issue by lpf123lpf** [LewinJun/react-native-lewin-qrcode#11]
![image](https://user-images.githubusercontent.com/43693771/84349470-fab33680-abe9-11ea-8570-70ac1b6b3382.png)
按照您的给的模版写的 但是选择完图片会报这个错误null is not object (evaluating 'QRScanReader.readerQr)

**Comment by lpf123lpf** [comment]
RN 0.6+应该不需要收到link吧

**Comment by LewinJun** [comment]
直接yarn add 应该就可以了，你可以看下iOS 以及android包管理里面是否有这个库

**Comment by 1871636671** [comment]
你好,我也遇到和你一样的问题了,请问你当时是怎么解决的?
