### ISSUE TITLE
本地编译正常 打包报错 ld: library not found for -lQRCode

### ISSUE THREAD

**Issue by Lunziyuan** [LewinJun/react-native-lewin-qrcode#4]
ld: library not found for -lQRCode
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by LewinJun** [comment]
稍等哈，  我正在发布项目，你急着打包吗？  晚上我解决好重新发布一下

**Comment by LewinJun** [comment]
解决了，不好意思，请更新到1.0.2版本
