### ISSUE TITLE
android 上使用带logo 的二维码解析出错 

### ISSUE THREAD

**Issue by vveyZhang** [LewinJun/react-native-lewin-qrcode#5]
最后定位到的错误原因：com.google.zxing.NotFoundException。
找到原因，但是不会java 自己修改代码后编译就错了，，希望大大看到了修复下这个问题。

**Comment by LewinJun** [comment]
zxing这个jar包 没有带进去

**Comment by LewinJun** [comment]
compile 'com.google.zxing:core:3.3.2'   你看下这个库是否加进来了

**Comment by LewinJun** [comment]
新版1.1可以尝试一下
