### ISSUE TITLE
安卓扫码会报错 

### ISSUE THREAD

**Issue by Lunziyuan** [LewinJun/react-native-lewin-qrcode#7]
![5741547433675_ pic](https://user-images.githubusercontent.com/31342448/51094584-49885100-17e9-11e9-9192-c3cf4b01f4dd.jpg)
react-native-lewin-qrcode版本 1.0.2
安卓稳定必先 ios则不会 不管图片中是否包含二维码

**Comment by LewinJun** [comment]
图片的url你给是什么样子的？

**Comment by Lunziyuan** [comment]
> 图片的url你给是什么样子的？

类似这种 “file:///storage/emulated/0/Android/data/com.efolix.MicroStore.merchant/files/Pictures/image-5b86908d-5463-4964-8477-1a2cc909e803.jpg”
把 "file:///" 去掉之后 ok了 
我先把issus关闭了 多谢

**Comment by LewinJun** [comment]
好的，这个我记下了，后面我程序里面优化下做好判断，对你造成困扰不好意思

**Comment by HeyShinner** [comment]
![image](https://user-images.githubusercontent.com/16172530/110729253-5550f000-8259-11eb-95f6-95df5ff7b41b.png)
我的 path 没有 file 前缀也报这个错哎 @LewinJun
